### ISSUE TITLE
help, change another page/screen

### ISSUE THREAD

**Issue by riloraspopo** [muzammilkhn/animated_drawer#1]
nevermind, its work, thanks

**Comment by fly-qp** [comment]
How?

**Comment by muzammilkhn** [comment]
Sir how can I help you? Please describe it.

**Comment by fly-qp** [comment]
I would like to know how to close the drawer and what’s the best way to switch the mainPage?

Thanks in advance
Patrick Prader
Am 8. Apr. 2021, 20:41 +0200 schrieb Muhammad Muzammil ***@***.***>:

Sir how can I help you? Please describe it.

**Comment by riloraspopo** [comment]
in 'homePageContent' you can fill with PageView(childern [page1,page2,...], controller: _controller).. to change page, change the value of controller pageview...
