### ISSUE TITLE
Need Control over button drawer icon (Icon &color)

### ISSUE THREAD

**Issue by 1AhmedYasser** [muzammilkhn/animated_drawer#2]
_openButton() {
    return IconButton(
        icon: Icon(
          Icons.menu,
          color: Color(0xFF1f186f), //  need control over this
        ),
        onPressed: () {
          HomePageBloc().openDrawer();
          ShadowBLOC().openDrawer();

          setState(() {});
          shadowState.setState(() {});
        });
  }

  _closeButton() {
    return IconButton(
        icon: Icon(Icons.arrow_back_ios, color: Color(0xFF1f186f)), //  need control over this
        onPressed: () {
          HomePageBloc().closeDrawer();
          ShadowBLOC().closeDrawer();

          setState(() {});
          shadowState.setState(() {});
        });
  }

**Comment by 1AhmedYasser** [comment]
Need the ability to change the drawer button icon and color

**Comment by muzammilkhn** [comment]
I have introduced optional **parameters** `openIcon` &  `closeIcon`. You can assign `Icon`,  `Image.asset` & `Image.network` to them. 

If you don't provide a **Widget** to `openIcon` &  `closeIcon` **parameters** then the **Default Widget** will be used respectively.

**Default Widget** for `openIcon`: `Icon(Icons.menu, color: Color(0xFF1f186f),)`.
**Default Widget** for `closeIcon`: `Icon(Icons.arrow_back_ios, color: Color(0xFF1f186f))`.
