### ISSUE TITLE
/example should contain the whole app

### ISSUE THREAD

**Issue by iqfareez** [muzammilkhn/animated_drawer#4]
For easy testing purposes. Developer can straight away `cd example; flutter run` in their terminal

**Comment by muzammilkhn** [comment]
An **App** is included now in **Example**, and  sample file is removed. The App can be launched directly now from its `main.dart`.

**Comment by muzammilkhn** [comment]
An **App** is included now in **Example**, and  sample file is removed. The App can be launched directly now from its `main.dart`.
